# Generated by Django 4.2.26 on 2025-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='static/media/img/')),
                ('description', models.TextField(db_index=True, max_length=400)),
                ('github_url', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('live_url', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
            options={
                'ordering': ('id',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
