# Generated by Django 4.2.26 on 2025-12-03 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_list', to='portfolio.project'),
        ),
    ]
